apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wiremock
  template:
    metadata:
      labels:
        app: wiremock
    spec:
      containers:
      - name: wiremock
        image: wiremock/wiremock:latest
        args:
        - --no-request-journal
        ports:
        - containerPort: 8080
